---

- name: Create custom fact directory
  file:
    path:  "{{ facts__dir|d('/etc/ansible/facts.d') }}"
    owner: root
    group: root
    mode:  0755
    state: directory
  tags: ['zabbix-server', 'zabbix-server-facts']

- name: Insert custom fact file
  template:
    src:   zabbix-server.py.fact.j2
    dest:  "{{ facts__dir|d('/etc/ansible/facts.d') }}/zabbix-server.fact"
    owner: root
    group: root
    mode:  0755
  tags: ['zabbix-server', 'zabbix-server-facts']
